### ISSUE TITLE
ppa cython bindings?

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/Tasks#35]
Does the ppa include the cython bindings? If not, could it be update to do so, or perhaps a pip package could be created?

I might be using the cython version much more heavily soon and compiling from source takes a long time to run on travis so there is less time to build the packages that depend on it.

**Comment by ahundt** [comment]
Also, the ppas don't seem to include the CMake config files. This means I can't actually use them right now. :-/

**Comment by gergondet** [comment]
The ppa includes the Python bindings in the `python-tasks` or `python3-tasks` package (note that the Python3 bindings are not extensively tested and there is probably plenty of broken functions, especially those that expect string arguments).

I'll look into the cmake config files. It should be easy to add them.

**Comment by ahundt** [comment]
Is that something I should be concerned about w.r.t. the python3 bindings for all dependencies (sva, rbdyn, etc) as well? 

I'm being forced to switch due to a couple packages I plan to use being python3 only.

**Comment by haudren** [comment]
I am afraid so, we are still mostly using `python2.7` here. However, those string issues are usually easy to fix in the userland code. nstead of doing:
> my_function("some string")

That will probably crash with a message saying that this function expects `bytes` and not a `string`.
Just do:
> my_function("some string".encode(u'ascii'))

**Comment by ahundt** [comment]
ah ok not too bad, thanks

**Comment by gergondet** [comment]
> Also, the ppas don't seem to include the CMake config files. This means I can't actually use them right now. :-/

That is solved now. All packages ship with the cmake config files (in the `*-dev` package). I'll close this issue now.

**Comment by ahundt** [comment]
Awesome, thanks! I'll give it a try
