### ISSUE TITLE
cmake python install setup.py --user

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/Tasks#36]
I might need an option to install via cmake in the user directory.  Perhaps it could be done with a cmake flag like `-DPYTHON_USER_INSTALL`?

In other words something like the following should eventually run:
```
python setup.py install --user
```

I think this also applies to everything tasks depends on too.

**Comment by gergondet** [comment]
It exists already. It's `PYTHON_BINDING_USER_INSTALL` it does what you described (works with all packages in the stack)

**Comment by ahundt** [comment]
whoops, I had missed it. Thanks!
