### ISSUE TITLE
Is it possible to speed up the CoM Jacobian calculation by generating the CoM Jacobian code?

### ISSUE THREAD

**Issue by oofrivia** [jrl-umi3218/Tasks#53]
Hi! I met with some problems with the Center Of Mass Jacobian for a humanoid robot.

It is easy to use CoMJacobian to calculate the CoM Jacobian, but it uses more than 1.5 milliseconds on an I5 Intel processor, and I want it to be faster, so I want to speed up the calculation by generating the CoM Jacobian code like this library do:
https://github.com/cdsousa/SymPyBotics
> rbt.kin.J[-1]
Matrix([
[0,        0],
[0,        0],
[0,        0],
[0, -cos(q1)],
[0, -sin(q1)],
[1,        0]])

Above is a two dof jacobian matrix. May I get a matrix like this, and I can use mbc.q to directly calculate the CoM Jacobian?  If it is possible, how could I get the 3x18  CoM Jacobian matrix?

Thanks a lot!

**Comment by gergondet** [comment]
Closing as this is related to RBDyn (see jrl-umi3218/RBDyn#58)
