### ISSUE TITLE
install of tasks interferes with rbdyn

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/Tasks#6]
It seems installing tasks overwrites (at least) the file from rbdyn `/usr/local/include/rbdyn/Body.h`

https://gist.github.com/0be8a6cc73f2333ef75522bb69c17aca

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/rbdyn/Body.h
Target /usr/local/include/rbdyn/Body.h
is a symlink belonging to rbdyn. You can unlink it:
  brew unlink rbdyn

To force the link and overwrite all conflicting files:
  brew link --overwrite tasks

To list all files that would be deleted:
  brew link --overwrite --dry-run tasks

```

**Comment by haudren** [comment]
This should not be possible, as the file Body.h is not present in Tasks. I checked in your repository and your formula for tasks still points to RBDyn. 

Wouldn't this be the problem? 

Cheers

**Comment by ahundt** [comment]
hah! whoops wasn't paying attention to what I was doing. Sorry!

**Comment by ahundt** [comment]
Okay I fixed it to install the correct repository, and now it isn't correctly locating sch-core.

https://gist.github.com/f90a71df10870002f4bb1030220628bb

I'm used to stuff that installs using the [packageConfig.cmake utilities built into cmake](https://cmake.org/cmake/help/v3.5/manual/cmake-packages.7.html#creating-packages), rather than the "old-school" pkg-config utility. 

**Any advice on how can I figure out the mismatch between the package I've installed and what pkg-config expects?**

The right headers seem to be installed:

```
± ls /usr/local/include/sch/*
/usr/local/include/sch/sch_api.h

/usr/local/include/sch/CD:
CD_Pair.h              CD_Simplex.h           CD_SimplexEnhanced.h   GJK.h
CD_Scene.h             CD_Simplex.hxx         CD_SimplexEnhanced.hxx

/usr/local/include/sch/CD_Penetration:
CD_Depth.h   DT_TriEdge.h

/usr/local/include/sch/File_Parsing:
SimplestParsing.h

/usr/local/include/sch/Matrix:
QuaternionT.h     SmallMatrix3x3T.h SmallVector3T.h
SCH_Types.h       SmallMatrix4x4T.h SmallVector4T.h

/usr/local/include/sch/STP-BV:
STP_BV.h          STP_BigSphere.h   STP_Feature.hxx   STP_Torus.h
STP_BV_P.h        STP_Feature.h     STP_SmallSphere.h

/usr/local/include/sch/S_Object:
S_Box.h                   S_ObjectNonNormalized.h   S_ObjectNormalized.hxx
S_Object.h                S_ObjectNonNormalized.hxx S_Sphere.h
S_Object.hxx              S_ObjectNormalized.h      S_Superellipsoid.h

/usr/local/include/sch/S_Polyhedron:
Polyhedron_algorithms.h S_PolyhedronVertex.h
S_Polyhedron.h          S_PolyhedronVertex.hxx

/usr/local/include/sch/core:
config.h      config.hh     deprecated.hh warning.hh
```

**Comment by ahundt** [comment]
The key lines are the pkg-config step:

```

-- sch-core is required.
-- Checking for module 'sch-core'
--   No package 'sch-core' found
CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindPkgConfig.cmake:363 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindPkgConfig.cmake:528 (_pkg_check_modules_internal)
  cmake/pkg-config.cmake:234 (PKG_CHECK_MODULES)
  cmake/pkg-config.cmake:316 (ADD_DEPENDENCY)
  CMakeLists.txt:27 (ADD_REQUIRED_DEPENDENCY)


-- Configuring incomplete, errors occurred!
See also "/tmp/tasks-20160519-26989-4o49t1/build/CMakeFiles/CMakeOutput.log".
```

**Comment by gergondet** [comment]
For pkg-config to find sch-core you need to have a sch-core.pc file in one of the folder in the paths of PKG_CONFIG_PATH + a few default paths (note: /usr/local/lib/pkgconfig should be within these default  paths). This file should be installed by sch-core so it seems strange that you have the headers there but not the .pc 

Your tasks formula looks like it is missing dependencies on rbdyn and sch-core

**Comment by haudren** [comment]
@ahundt : I think you solved this, I'll close the issue.

**Comment by ahundt** [comment]
yes, thanks!
