### ISSUE TITLE
Dimensional stiffness

### ISSUE THREAD

**Issue by Saeed-Mansouri** [jrl-umi3218/Tasks#78]
Is it possible we have a dimensional stiffness for PostureTask?

**Comment by gergondet** [comment]
Hi @Saeed-Mansouri 

It's already possible via [`tasks::qp::PostureTask::jointStiffness`](https://github.com/jrl-umi3218/Tasks/blob/master/src/Tasks/QPTasks.h#L507) you can set specific stiffness for specific joints (the joint stiffness is not additive, it overwrites the task stiffness for a given joint)
